config/routes.rb
Rails.application.routes.draw do
  resources :study_sets
  resources :card_sets
  resources :group_reviews
  resources :card_reviews
  resources :groups
  get 'users/show'
  root 'static_pages#home'
  get 'static_pages/home'
  devise_for :users
  resources :cards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :user
    belongs_to :group
    has_one_attached :picture
    has_many :card_review, -> { order "created_at DESC"}
end

app/models/card_review.rb
class CardReview < ApplicationRecord
    belongs_to :user
    belongs_to :card
end

app/models/card_set.rb
class CardSet < ApplicationRecord
end

app/models/cards_review.rb
class CardsReview < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
    belongs_to :user
    has_many :card
    has_many :group_review, -> { order "created_at DESC"}
end

app/models/group_review.rb
class GroupReview < ApplicationRecord
    belongs_to :user
    belongs_to :group
end

app/models/study_set.rb
class StudySet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  has_many :group
  validates :name, presence: true
  validates :age, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card_review = CardReview.new
  end

  # GET /cards/new
  def new
    @card = Card.new
    @group = Group.all
  end

  # GET /cards/1/edit
  def edit
    @group = Group.all
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    @card.group_id = params[:group_id]
    @card.user_id = current_user.id
    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    @card.group_id = params[:group_id]
    @card.user_id = current_user.id
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:front_side, :back_side, :group_id, :user_id, :picture, :review)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    
    @id = @group.id
    @cards = Card.where("group_id = ?" , @id)
    @group_review = GroupReview.new
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:user_id, :name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_reviews_helper.rb
module CardReviewsHelper
end

app/helpers/card_sets_helper.rb
module CardSetsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cards_reviews_helper.rb
module CardsReviewsHelper
end

app/helpers/group_reviews_helper.rb
module GroupReviewsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sets_helper.rb
module SetsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/study_sets_helper.rb
module StudySetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "言葉", class:"text-blod" %>
    <%= form.text_field :front_side, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label "意味"%>
    <%= form.text_field :back_side, class:"form-control" %>
  </div>
  
  <div class="field">
    <%= form.label "イラストの画像", class:"text-blod" %>
    <%= form.file_field :picture, class:"form-control" %>
  </div>
  
  <div class="field">
    <%= form.label "セット" %>
    <%= select_tag :group_id, options_for_select(@group.collect{ |g| [g.name, g.id] }), class: 'form-control' %>
  </div>
  

  <div class="actions">
    <p class="btn btn-secondary btn-block"><%= form.submit %></p>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1 class ="text-center bg-white font-italic">Editing Card</h1>

<%= render 'form', card: @card %>


<div class="row text-white">
  <div class="col-md-6 text-light">
    <%= link_to 'Show', @card, class:"btn btn-sm btn-outline-secondary btn-block" %>
  </div>
  <div class="col-md-6">
    <%= link_to 'Back', cards_path, class:"btn btn-sm btn-outline-secondary btn-block" %>
  </div>
</div>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Card', new_card_path, class:"text-right btn btn-outline-success btn-sm text-dark"%>
<h1 class ="text-center bg-white font-italic">
  Cards
</h1>

<table class="table table-striped" style="margin-left: 0px">
  <thead class="thead-dark">
    <tr>
      <th scope="col" class ="text-center">言葉</th>
      <th scope="col" class ="text-center" colspan="6">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td>
          <div class="card">
            <div id="show-back-<%= card.id %>" class="card-body text-primary font-weight-bold">
              <%= card.front_side %>
            </div>
          </div>
        </td>
        <td><%= link_to 'Detail', card, class:"btn btn-outline-secondary btn-sm" %></td>
        <td><button onclick="myFunction(<%= card.id %>, '<%= card.back_side %>', '<%= card.front_side %>')" type="button" class="btn btn-outline-primary btn-sm">Quick view</button><td>
        <td><%= link_to 'Edit', edit_card_path(card), class:"btn btn-outline-warning btn-sm" %></td>
        <td><%= link_to 'Destroy', card, method: :delete, class:"btn btn-outline-danger btn-sm", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>






<script>

function myFunction(id, mean, term) {
  console.log(mean);
  var element = document.getElementById("show-back-"+id);
  if($(element).hasClass( "text-primary" ) == true)
  {
    $(element).removeClass("text-primary");
    $(element).addClass("text-success");
    $(element).text(mean);
  }else{
    $(element).addClass("text-primary");
    $(element).removeClass("text-success");
    $(element).text(term);
  }
}
</script>

app/views/cards/new.html.erb
<h1 class ="text-center bg-white font-italic">New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path, class:"btn btn-secondary text-light" %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <% if @card.picture.attached? %>
        <%= image_tag @card.picture, style:"height: 350px" %>
      <% end %>
      <div class="card-body">
        <h5 class="card-title"><%= @card.group.name %></h5>
        <p class="card-text">By <%= @card.user.name %> at <%= @card.created_at %></p>
      </div>
    </div>
  </div>
</div>
<div class="row text-center">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <strong>言葉</strong>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= @card.front_side %></h5>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <strong>意味</strong>
      </div>
    <div class="card-body">
    <h5 class="card-title"><%= @card.back_side %></h5>
    </div>
  </div>
  </div>
</div>
<h3 class ="text-center bg-white font-italic">このカード、どう？</h3>
 <%= form_with(model: @card_review, local: true) do |form| %>
   <div class= "field">
     <%= form.text_area :review, class:"form-control" %>
     <%= form.hidden_field :card_id, :value => @card.id %>
   </div>
   <div class="actions">
     <p class="btn btn-secondary btn-sm"><%= form.submit %></p>
   </div>
 <% end %>
 <h4 class ="text-center bg-white font-italic">読者 コーナー</h4>
  <% @card.card_review.each do |card_review|%>
    <div class="media">
      <% if card_review.user.avatar.attached? %>
        <%= image_tag card_review.user.avatar, class:"align-self-start mr-3", style:"width:64px; height:64px"%>
      <% end %>
      <div class="media-body">
        <h5 class="mt-0"><%= card_review.user.name %></h5>
        <p><%= card_review.review %></p>
      </div>
    </div>
  <% end %>
  
  
  
<br></br>
<div class="row text-white">
  <div class="col-md-6 text-light">
    <%= link_to 'Edit', edit_card_path(@card), class:"btn btn-sm btn-outline-secondary btn-block" %>
  </div>
  <div class="col-md-6">
    <%= link_to 'Back', cards_path, class:"btn btn-sm btn-outline-secondary btn-block" %>
  </div>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="actions">
    <p class="btn btn-secondary btn-block"><%= form.submit %></p>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1 class ="text-center bg-white font-italic">Editing Group</h1>

<%= render 'form', group: @group %>

<div class="row text-white">
  <div class="col-md-6 text-light">
    <%= link_to 'Show', @group, class:"btn btn-sm btn-outline-secondary btn-block" %>
  </div>
  <div class="col-md-6">
    <%= link_to 'Back', groups_path, class:"btn btn-sm btn-outline-secondary btn-block" %>
  </div>
</div>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Group', new_group_path, class:"text-right btn btn-outline-success btn-sm text-dark"%>
<h1 class ="text-center bg-white font-italic">
  Groups
</h1>

<table class="table table-striped" style="margin-left: 0px">
  <thead>
    <tr>
      <th>メーカー</th>
      <th>セットの名前</th>
      <th class="text-center" colspan="3">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.user.name %></td>
        <td><%= group.name %></td>
        <td><%= link_to 'Show', group, class:"btn btn-sm btn-outline-primary btn-sm" %></td>
        <td><%= link_to 'Edit', edit_group_path(group), class:"btn btn-sm btn-outline-warning btn-sm" %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/new.html.erb
<h1 class ="text-center bg-white font-italic">New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path, class:"btn btn-secondary text-light" %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card text-center">
  <div class="card-header">
    Creater: <%= @group.user.name %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><strong><%= @group.name %></strong></h5>
  </div>
  <div class="card-footer text-muted">
    Created at <%= @group.created_at %>
  </div>
</div>


<table class="table table-striped" style="margin-left: 0px">
  <thead class="thead-dark">
    <tr>
      <th scope="col" class ="text-center">言葉</th>
      <th scope="col" class ="text-center" colspan="6">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td>
          <div class="card">
            <div id="show-back-<%= card.id %>" class="card-body text-primary font-weight-bold">
              <%= card.front_side %>
            </div>
          </div>
        </td>
        <td><%= link_to 'Detail', card, class:"btn btn-outline-secondary btn-sm" %></td>
        <td><button onclick="myFunction(<%= card.id %>, '<%= card.back_side %>', '<%= card.front_side %>')" type="button" class="btn btn-outline-primary btn-sm">Quick view</button><td>
        <td><%= link_to 'Edit', edit_card_path(card), class:"btn btn-outline-warning btn-sm" %></td>
        <td><%= link_to 'Destroy', card, method: :delete, class:"btn btn-outline-danger btn-sm", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h4>Review From</h2>
 <%= form_with(model: @group_review, local: true) do |form| %>
   <div class= "field">
     <%= form.text_area :review %>
     <%= form.hidden_field :group_id, :value => @group.id %>
   </div>
   <div class="actions">
     <%= form.submit %>
   </div>
 <% end %>
 <h2>Review List</h2>
     <ul>
       <% @group.group_review.each do |group_review|%>
        <li><%= group_review.review %>
          (<i><%= group_review.user.name %></i>)</li>
     <% end %>
     </ul>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

<script>

function myFunction(id, mean, term) {
  console.log(mean);
  var element = document.getElementById("show-back-"+id);
  if($(element).hasClass( "text-primary" ) == true)
  {
    $(element).removeClass("text-primary");
    $(element).addClass("text-success");
    $(element).text(mean);
  }else{
    $(element).addClass("text-primary");
    $(element).removeClass("text-success");
    $(element).text(term);
  }
}
</script>

app/views/users/show.html.erb
<h1 class ="text-center bg-white font-italic">Profile</h1>


<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="card text-center" style="width: 18rem;">
      <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar, style:"width:287px" %>
      <% end %>
      <div class="card-body">
        <h5 class="card-title"><%= @user.name %></h5>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= @user.age %>歳</li>
        <li class="list-group-item">Eメール：<%= @user.email %></li>
      </ul>
      <div class="card-body">
        <%= link_to 'Edit', edit_user_registration_path %> | <%= link_to "Back", :back %>
      </div>
    </div>
  </div>
</div>