config/routes.rb
Rails.application.routes.draw do
  resources :study_sets
  resources :card_sets
  resources :group_reviews
  resources :card_reviews
  resources :groups
  get 'users/show'
  root 'static_pages#home'
  get 'static_pages/home'
  devise_for :users
  resources :cards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :user
    belongs_to :group
    has_one_attached :picture
    has_many :card_review, -> { order "created_at DESC"}
end

app/models/card_review.rb
class CardReview < ApplicationRecord
    belongs_to :user
    belongs_to :card
end

app/models/card_set.rb
class CardSet < ApplicationRecord
end

app/models/cards_review.rb
class CardsReview < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
    belongs_to :user
    has_many :card
    has_many :group_review, -> { order "created_at DESC"}
end

app/models/group_review.rb
class GroupReview < ApplicationRecord
    belongs_to :user
    belongs_to :group
end

app/models/study_set.rb
class StudySet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  has_many :group
  validates :name, presence: true
  validates :age, presence: true
end

app/controllers/card_reviews_controller.rb
class CardReviewsController < ApplicationController
  before_action :set_card_review, only: [:show, :edit, :update, :destroy]

  # GET /card_reviews
  # GET /card_reviews.json
  def index
    @card_reviews = CardReview.all
  end

  # GET /card_reviews/1
  # GET /card_reviews/1.json
  def show
  end

  # GET /card_reviews/new
  def new
    @card_review = CardReview.new
  end

  # GET /card_reviews/1/edit
  def edit
  end

  # POST /card_reviews
  # POST /card_reviews.json
  def create
    @card_review = CardReview.new(card_review_params)
    @card_review.user_id = current_user.id
    respond_to do |format|
      if @card_review.save
        url = "/cards/" + @card_review.card_id.to_s
        format.html { redirect_to url, notice: 'Book review was successfully created.' }
        format.json { render :show, status: :created, location: @card_review }
      else
        format.html { render :new }
        format.json { render json: @card_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /card_reviews/1
  # PATCH/PUT /card_reviews/1.json
  def update
    respond_to do |format|
      if @card_review.update(card_review_params)
        format.html { redirect_to @card_review, notice: 'Card review was successfully updated.' }
        format.json { render :show, status: :ok, location: @card_review }
      else
        format.html { render :edit }
        format.json { render json: @card_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /card_reviews/1
  # DELETE /card_reviews/1.json
  def destroy
    @card_review.destroy
    respond_to do |format|
      format.html { redirect_to card_reviews_url, notice: 'Card review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card_review
      @card_review = CardReview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_review_params
      params.require(:card_review).permit(:user_id, :card_id, :review)
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card_review = CardReview.new
  end

  # GET /cards/new
  def new
    @card = Card.new
    @group = Group.all
  end

  # GET /cards/1/edit
  def edit
    @group = Group.all
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    @card.group_id = params[:group_id]
    @card.user_id = current_user.id
    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    @card.group_id = params[:group_id]
    @card.user_id = current_user.id
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:front_side, :back_side, :group_id, :user_id, :picture, :review)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_reviews_helper.rb
module CardReviewsHelper
end

app/helpers/card_sets_helper.rb
module CardSetsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cards_reviews_helper.rb
module CardsReviewsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sets_helper.rb
module SetsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/study_sets_helper.rb
module StudySetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/card_reviews/_form.html.erb
<%= form_with(model: card_review, local: true) do |form| %>
  <% if card_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card_review.errors.count, "error") %> prohibited this card_review from being saved:</h2>

      <ul>
        <% card_review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :card_id %>
    <%= form.number_field :card_id %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_area :review %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/card_reviews/edit.html.erb
<h1>Editing Card Review</h1>

<%= render 'form', card_review: @card_review %>

<%= link_to 'Show', @card_review %> |
<%= link_to 'Back', card_reviews_path %>

app/views/card_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Card Reviews</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Card</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @card_reviews.each do |card_review| %>
      <tr>
        <td><%= card_review.user.name %></td>
        <td><%= card_review.card.front_side %>|<%= card_review.card.back_side %></td>
        <td><%= card_review.review %></td>
        <td><%= link_to 'Show', card_review %></td>
        <td><%= link_to 'Edit', edit_card_review_path(card_review) %></td>
        <td><%= link_to 'Destroy', card_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card Review', new_card_review_path %>

app/views/card_reviews/new.html.erb
<h1>New Card Review</h1>

<%= render 'form', card_review: @card_review %>

<%= link_to 'Back', card_reviews_path %>

app/views/card_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @card_review.user.name %>
</p>

<p>
  <strong>Card:</strong>
  <%= @card_review.card.front_side %> - <%= @card_review.card.back_side %>
</p>

<p>
  <strong>Review:</strong>
  <%= @card_review.review %>
</p>

<%= link_to 'Edit', edit_card_review_path(@card_review) %> |
<%= link_to 'Back', card_reviews_path %>